services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
        - "3306:3306"
    volumes:
        - mysql-data:/var/lib/mysql

volumes:
    mysql-data: