import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "todo app",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" >
      <body suppressHydrationWarning={true} className={inter.className} >
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
